apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-access-sa
  namespace: access # This ServiceAccount is created in the 'access' namespace and can be used to grant specific permissions to pods running in that namespace.