apiVersion: v1
kind: Pod
metadata:
  labels:
    run: service-account-demo-pod
  name: service-account-demo-pod
  namespace: access
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: busybox
    name: service-account-demo-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: limited-access-sa # This pod is configured to use the 'limited-access-sa' ServiceAccount, which is created in the 'access' namespace. This allows the pod to inherit the permissions associated with that ServiceAccount, enabling it to perform actions defined by the roles and role bindings assigned to 'limited-access-sa'.
  serviceAccountName: limited-access-sa # This field explicitly specifies the ServiceAccount to be used by the pod, ensuring that it operates with the permissions granted to 'limited-access-sa' in the 'access' namespace.
