apiVersion: v1
kind: Pod
metadata:
  labels:
    run: toleration-test-fail
  name: toleration-test-fail
spec:
  containers:
  - image: nginx
    name: toleration-test-fail
    resources:
      requests:
        memory: 32Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "app"
    effect: "NoSchedule"
