apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/persistent-volume" # path must exist on host